sydneyTrainsClass.prototype.lines.BlueMountains = [
	{"order":1, "name":"Central"},
	{"order":2, "name":"Redfern"},
	{"order":3, "name":"Strathfield"},
	{"order":4, "name":"Parramatta"},
	{"order":5, "name":"Blacktown"},
	{"order":6, "name":"Penrith"},
	{"order":7, "name":"Emu Plains"},
	{"order":8, "name":"Lapstone"},
	{"order":9, "name":"Glenbrook"},
	{"order":10, "name":"Blaxland"},
	{"order":11, "name":"Warrimoo"},
	{"order":12, "name":"Valley Heights"},
	{"order":13, "name":"Springwood"},
	{"order":14, "name":"Faulconbridge"},
	{"order":15, "name":"Linden"},
	{"order":16, "name":"Woodford"},
	{"order":17, "name":"Hazelbrook"},
	{"order":18, "name":"Lawson"},
	{"order":19, "name":"Bullaburra"},
	{"order":20, "name":"Wentworth Falls"},
	{"order":21, "name":"Leura"},
	{"order":22, "name":"Katoomba"},
	{"order":23, "name":"Medlow Bath"},
	{"order":24, "name":"Blackheath"},
	{"order":25, "name":"Mount Victoria"},
	{"order":26, "name":"Bell"},
	{"order":27, "name":"Zig Zag"},
	{"order":28, "name":"Lithgow"},
	{"order":29, "name":"Bathurst"}
];