sydneyTrainsClass.prototype.lines.CentralCoastViaGordon = [
	{"order":1, "name":"Central"},
	{"order":2, "name":"Redfern"},
	{"order":3, "name":"Strathfield"},
	{"order":4, "name":"Eastwood},
	{"order":5, "name":"Epping"},
	{"order":6, "name":"Hornsby"},
	{"order":7, "name":"Asquith"},
	{"order":8, "name":"Mount Colah"},
	{"order":9, "name":"Mount Kuring-gai"},
	{"order":10, "name":"Berowra"},
	{"order":11, "name":"Cowan"},
	{"order":12, "name":"Hakesbury River"},
	{"order":13, "name":"Wondabyne"},
	{"order":14, "name":"Woy Woy"},
	{"order":15, "name":"Koolewong"},
	{"order":16, "name":"Tascott"},
	{"order":17, "name":"Point Clare"}
	{"order":18, "name":"Gosford"},
	{"order":19, "name":"Narara"},
	{"order":20, "name":"Niagara Park"},
	{"order":21, "name":"Lisarow"},
	{"order":22, "name":"Ourimbah"},
	{"order":23, "name":"Tuggerah"},
	{"order":24, "name":"Wyong"},
	{"order":25, "name":"Warnervale"},
	{"order":26, "name":"Wyee"},
	{"order":27, "name":"Morisset"},
	{"order":28, "name":"Dora Creek"},
	{"order":29, "name":"Awaba"},
	{"order":30, "name":"Fassifern"},
	{"order":31, "name":"Booragul"},
	{"order":32, "name":"Teralba"},
	{"order":33, "name":"Cockle Creek"},
	{"order":34, "name":"Cardiff"},
	{"order":35, "name":"Kotara"},
	{"order":36, "name":"Adamstown"},
	{"order":37, "name":"Broadmeadow"},
	{"order":38, "name":"Hamilton"}
];