sydneyTrainsClass.prototype.lines.HunterDungog = [
	{"order":1, "name":"Hamilton"},
	{"order":2, "name":"Waratah"},
	{"order":3, "name":"Warabrook"},
	{"order":4, "name":"Sandgate"},
	{"order":5, "name":"Hexham"},
	{"order":6, "name":"Tarro"},
	{"order":7, "name":"Beresfield"},
	{"order":8, "name":"Thornton"},
	{"order":9, "name":"Metford"},
	{"order":10, "name":"Victoria Street"},
	{"order":11, "name":"East Maitland"},
	{"order":12, "name":"High Street"},
	{"order":13, "name":"Maitland"},
	{"order":14, "name":"Telarah"},
	{"order":15, "name":"Mindaribba"},
	{"order":16, "name":"Paterson"},
	{"order":17, "name":"Martins Creek"},
	{"order":18, "name":"Hilldale"},
	{"order":19, "name":"Wallarobba"},
	{"order":20, "name":"Wirragulla"},
	{"order":21, "name":"Dungog"}
];