sydneyTrainsClass.prototype.lines.SouthernHighlands = [
	{"order":1, "name":"Central"},
	{"order":2, "name":"Redfern"},
	{"order":3, "name":"Wolli Creek"},
	{"order":4, "name":"Campbelltown"},
	{"order":5, "name":"Macarthur"},
	{"order":6, "name":"Menangle Park"},
	{"order":7, "name":"Menangle"},
	{"order":8, "name":"Douglas Park"},
	{"order":9, "name":"Picton"},
	{"order":10, "name":"Tahmoor"},
	{"order":11, "name":"Bargo"},
	{"order":12, "name":"Yerrinbool"},
	{"order":13, "name":"Mittagong"},
	{"order":14, "name":"Bowral"},
	{"order":15, "name":"Burradoo"},
	{"order":16, "name":"Moss Vale"},
	{"order":17, "name":"Exeter"},
	{"order":18, "name":"Bundanoon"},
	{"order":19, "name":"Penrose"},
	{"order":20, "name":"Wingello"},
	{"order":21, "name":"Tallong"},
	{"order":22, "name":"Marulan"},
	{"order":23, "name":"Goulburn"}
];