sydneyTrainsClass.prototype.lines.SouthCoastBomaderry = [
	{"order":1, "name":"Bondi Junction"},
	{"order":2, "name":"Edgecliff"},
	{"order":3, "name":"Kings Cross"},
	{"order":4, "name":"Martin Place"},
	{"order":5, "name":"Town Hall"},
	{"order":6, "name":"Central"},
	{"order":7, "name":"Redfern"},
	{"order":8, "name":"Wolli Creek"},
	{"order":9, "name":"Hurtville"},
	{"order":10, "name":"Sutherland"},
	{"order":11, "name":"Waterfall"},
	{"order":12, "name":"Helensburgh"},
	{"order":13, "name":"Otford"},
	{"order":14, "name":"Stanwell Park"},
	{"order":15, "name":"Coalcliff"},
	{"order":16, "name":"Scarborough"},
	{"order":17, "name":"Wombarra"},
	{"order":18, "name":"Coledale"},
	{"order":19, "name":"Austinmer"},
	{"order":20, "name":"Thirroul"},
	{"order":21, "name":"Bulli"},
	{"order":22, "name":"Woonona"},
	{"order":23, "name":"Bellambi"},
	{"order":24, "name":"Corrimal"},
	{"order":25, "name":"Towradgi"},
	{"order":26, "name":"Fairy Meadow"},
	{"order":27, "name":"North Wollongong"},
	{"order":28, "name":"Wollongong"},
	{"order":29, "name":"Coniston"},
	{"order":30, "name":"Unanderra"},
	{"order":31, "name":"Kembla Grange"},
	{"order":32, "name":"Dapto"},
	{"order":33, "name":"Albion Park"},
	{"order":34, "name":"Oak Flats"},
	{"order":35, "name":"Shellharbour Junction"},
	{"order":36, "name":"Minnamurra"},
	{"order":37, "name":"Bombo"},
	{"order":38, "name":"Kiama"},
	{"order":39, "name":"Gerringong"},
	{"order":40, "name":"Berry"},
	{"order":41, "name":"Bomaderry"}
];